# Generated by Django 4.0.3 on 2022-04-07 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_group_code_group_year_alter_group_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialization',
            name='group',
        ),
    ]
