# Generated by Django 4.0.3 on 2022-04-13 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='subject',
            field=models.ManyToManyField(related_name='student', to='main.subject'),
        ),
    ]
