# Generated by Django 4.0.3 on 2022-04-13 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_subject_group_alter_student_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.group'),
            preserve_default=False,
        ),
    ]
