# Generated by Django 4.0.5 on 2022-06-05 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_subject_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='specializetion',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.specialization'),
        ),
    ]
