# Generated by Django 4.0.3 on 2022-04-13 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_group_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='main.group'),
        ),
    ]
