# Generated by Django 4.0.3 on 2022-04-13 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_specialization_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialization',
            name='group',
        ),
    ]
