# Generated by Django 4.0.3 on 2022-04-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_specialization_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='group',
            field=models.ManyToManyField(related_name='specs', to='main.group'),
        ),
    ]
