# Generated by Django 4.0.3 on 2022-04-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_specialization_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='faculty',
        ),
        migrations.AddField(
            model_name='subject',
            name='faculty',
            field=models.ManyToManyField(related_name='subjects', to='main.specialization'),
        ),
    ]
