# Generated by Django 4.0.3 on 2022-04-16 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_subject_faculty_subject_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialization',
            name='group',
        ),
    ]
