# Generated by Django 4.0.4 on 2022-05-11 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_subject_semester_alter_subject_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='year',
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='main.semester'),
            preserve_default=False,
        ),
    ]
