# Generated by Django 4.0.4 on 2022-05-11 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_group_year_subject_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cgpa',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sgpa1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sgpa2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='subject',
        ),
        migrations.AddField(
            model_name='subject',
            name='credit',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Assignments', models.PositiveIntegerField(null=True)),
                ('Mid_Term', models.PositiveIntegerField(null=True)),
                ('End_Term', models.PositiveIntegerField(null=True)),
                ('Grade', models.CharField(blank=True, max_length=5, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='main.student')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.subject')),
            ],
        ),
    ]
