# Generated by Django 4.0.4 on 2022-05-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_student_cgpa_remove_student_sgpa1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cgpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sgpa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
